// <auto-generated />
using System;
using CloudShift.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CloudShift.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CloudShift.Domain.Entities.AppProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Provider")
                        .HasColumnType("int");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AppProfiles");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.FileTransferLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MigrationJobId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("SourceFileId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TransferredAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MigrationJobId", "Status")
                        .HasDatabaseName("IX_FileTransferLog_JobId_Status");

                    b.ToTable("FileTransferLogs");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.MigrationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobType")
                        .HasColumnType("int");

                    b.Property<int>("ProcessedItems")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectMappingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TotalItems")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectMappingId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_MigrationJob_Status");

                    b.ToTable("MigrationJobs");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.ProjectMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConflictResolutionRule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DestPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DestProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FilterConfigJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SourceProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DestProfileId");

                    b.HasIndex("SourceProfileId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ProjectMapping_UserId");

                    b.ToTable("ProjectMappings");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.AppProfile", b =>
                {
                    b.HasOne("CloudShift.Domain.Entities.User", "User")
                        .WithMany("AppProfiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.FileTransferLog", b =>
                {
                    b.HasOne("CloudShift.Domain.Entities.MigrationJob", "MigrationJob")
                        .WithMany("FileTransferLogs")
                        .HasForeignKey("MigrationJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MigrationJob");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.MigrationJob", b =>
                {
                    b.HasOne("CloudShift.Domain.Entities.ProjectMapping", "ProjectMapping")
                        .WithMany("MigrationJobs")
                        .HasForeignKey("ProjectMappingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectMapping");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.ProjectMapping", b =>
                {
                    b.HasOne("CloudShift.Domain.Entities.AppProfile", "DestProfile")
                        .WithMany()
                        .HasForeignKey("DestProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CloudShift.Domain.Entities.AppProfile", "SourceProfile")
                        .WithMany()
                        .HasForeignKey("SourceProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CloudShift.Domain.Entities.User", "User")
                        .WithMany("ProjectMappings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DestProfile");

                    b.Navigation("SourceProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.MigrationJob", b =>
                {
                    b.Navigation("FileTransferLogs");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.ProjectMapping", b =>
                {
                    b.Navigation("MigrationJobs");
                });

            modelBuilder.Entity("CloudShift.Domain.Entities.User", b =>
                {
                    b.Navigation("AppProfiles");

                    b.Navigation("ProjectMappings");
                });
#pragma warning restore 612, 618
        }
    }
}
